server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: offers-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/offers/sales/**
        - id: orders-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/orders/**
